# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-job:
    docker:
      - image: arbornetworks-docker-public-docker.bintray.io/circleci-node-aws:8.4.0
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build

  test-job:
    docker:
        - image: arbornetworks-docker-public-docker.bintray.io/circleci-node-aws:8.4.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn test

  deploy-job:
    docker:
      - image: arbornetworks-docker-public-docker.bintray.io/circleci-node-aws:8.4.0
    working_directory: ~/repo
    steps:
      - run: aws s3 sync dist s3://labsoft-webapp && aws cloudfront create-invalidation --distribution-id E15SSF7A27C5IK --paths '/*'
      
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - test-job:
          requires:
            - build-job
      - hold:
          type: approval
          requires:
            - test-job
      - deploy-job:
        requires:
          - hold