    version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: arbornetworks-docker-public-docker.bintray.io/circleci-node-aws:8.4.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - deploy:
          command: aws s3 sync dist s3://labsoft-webapp && aws cloudfront create-invalidation --distribution-id E15SSF7A27C5IK --paths '/*'